const ERROR_CODE_SERVER_ERROR = '1';
const ERROR_CODE_USER_NOT_FOUND = '2';
const ERROR_CODE_USER_ALREADY_EXIST = '3';
const ERROR_CODE_NICKNAME_ALREADY_EXIST = '4';
const ERROR_CODE_POST_NOT_FOUND = '5';
const ERROR_CODE_COMMENTS_CREATE_VALIDATION = '6';
const ERROR_CODE_COMMENTS_GET_VAlIDATION = '7';

module.exports = {
  ERROR_CODE_SERVER_ERROR,
  ERROR_CODE_USER_NOT_FOUND,
  ERROR_CODE_USER_ALREADY_EXIST,
  ERROR_CODE_NICKNAME_ALREADY_EXIST,
  ERROR_CODE_POST_NOT_FOUND,
  ERROR_CODE_COMMENTS_CREATE_VALIDATION,
  ERROR_CODE_COMMENTS_GET_VAlIDATION
}
